### PR TITLE
Feature/project structure - Milestone-1

### PR DESCRIPTION
**Pull request by rna**
# Hello :hand:

The first milestone completed.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @rna 👋

**Good work so far on this,👍**

**STATUS: CHANGES REQUIRED. 👷‍♂️**

- [x] Please fix the linting issues in your repo, before requesting a new review.

- [x] There are still some unnecessary files and assets in your project. Kindly remove the following files: 
- `public/logo512.png`
- `src/logo.svg`

- [x] Consider adding `src/serviceWorker.js` to your `.eslintrc.json` ignorePatterns section to avoid it being checked.

- [x] Please include the [`big.js`](https://github.com/MikeMcl/big.js/) package in your package.json. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/big.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

- [ ] Please ensure your app is deployed on Heroku and the live link is included in your README file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-deployed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by rna** [comment]
# Hello

Addressed the mentioned issues. Deployed to Heroku 
[Link](https://rna-calculator.herokuapp.com)

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @rna :hand: 
Great job working on the requested changes. 
But we also need to add a descriptive README file to your project.

- [ ] We need to change your README file from the one bootstrapped by `create-react-app` to a descriptive one with relevant information about your project. You can use this template [here](https://github.com/microverseinc/readme-template).
Screenshot from 2020-09-29 16-18-37

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

**Review by shloch — APPROVED** [review]
## Hello @rna 

Great work with the README UPDATES
accomplished

This milestone can be merged...now after setup ...let's get to coding

THUMBS UP

**Pull request merged**
